sudo: false

language: cpp

os: linux

env: 
  matrix: 
     - CONDA_PY=3.6
     - CONDA_PY=3.7
     - CONDA_PY=3.8


dist: trusty

install:
  - sudo apt-get update
  - ldd --version
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - rm -f miniconda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels slsdetectorgroup
  - conda update -q conda
  - conda info -a

  # Useful for debugging any issues with conda
  - conda create -q -n testenv python=$CONDA_PY conda-build anaconda-client conda-verify
  - conda activate testenv
  - conda-build .

script:
 - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2


deploy:
  provider: script
  script: find $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64 -name "*.tar.bz2" -exec anaconda -t $CONDA_TOKEN upload --force {} \;
  on:
    branch: udp

